# Generated by Django 5.1.1 on 2024-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synfinity24", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="octave",
            name="accTeacher",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std1Class",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std1Name",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std2Class",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std2Name",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std3Class",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std3Name",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std4Class",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="std4Name",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="teacherEmail",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="teamEmail",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="octave",
            name="teamName",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="octave",
            name="schoolEmail",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="octave",
            name="schoolName",
            field=models.TextField(),
        ),
    ]
