# Generated by Django 5.1.1 on 2024-10-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synfinity24", "0004_enigma_std2class_enigma_std2name_enigma_teamname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resonance",
            name="std3Class",
        ),
        migrations.RemoveField(
            model_name="resonance",
            name="std3Name",
        ),
    ]
